name: dogma_codegen_model
version: 0.0.1
description: Code generation of models for the Dogma libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
environment:
  sdk: '>=1.14.0-any <2.0.0'
dependencies:
  build:
    path: ../build
  dogma_convert:
    path: ../dogma-convert
  dogma_codegen:
    path: ../dogma-codegen
  dogma_source_analyzer:
    path: ../dogma-source-analyzer
  logging: ^0.11.1+1
  meta: ^0.10.0
dev_dependencies:
  test: ^0.12.3+9
  dogma_codegen_test:
    path: ../dogma-codegen-test
